PIC-4117: Update dependencies: spring boot, application-insights and xjc (#185)
* Migrate application insights to v3

Migrate application insights to major version 3 of
applicationinsights-web

Remove applicationinsights appender from logback

* Add APPLICATIONINSIGHTS_CONNECTION_STRING env

Add the environment variable APPLICATIONINSIGHTS_CONNECTION_STRING
which contains the applicationinsights connection string
pulled from the k8s secret for preprod and prod

* Update implementation of ContextInitialiser

* Remove applicationinsight logback appender

This is because applicationinsights logback is autoconfigured
in version 3

* Update bytebuddy version

* Upgrade dependencies for spring boot 3.3

Upgrade to Spring Boot version 3.3

Upgrade kotlin to version 2

Upgrade java to version 21

Upgrade xjc related tools and fix a transitive dependency by explicitly
setting the below:
    - xjcTool("com.sun.xml.bind:jaxb-xjc:2.3.3")
    - xjcTool("com.sun.xml.bind:jaxb-impl:2.3.3")

* Upgrade to java 21

* Upgrade to gradle version 8.5

* Fix ktlint linting issues

* Update junit and add javax dependencies

Add javax dependency back in as it's being used by a package
pulled in from magistrates library

Update the junit dependency to fix the below error after updating
the spring boot version:

java.lang.NoClassDefFoundError: org/junit/jupiter/api/io/TempDirFactory

* Migrate from javax to jakarta packages

* Use javax packages to map xml to java

This is because we pull in a package from http://www.justice.gov.uk/magistrates/
which uses javax for mapping xml.

TODO: request the library to update to using jakarta for xml mapping

* Fix docker-compose

* Migrate to jakarta.xml.bind:jakarta.xml.bind-api

This is after migrating to spring version 3.3

More info here at github:
unbroken-dome/gradle-xjc-plugin/blob/8acbcda4517121d7329ae3aef777bccfc8c7dc67/docs/xjc-versions.adoc

* Migrate to jakarta.xml.bind-api from javax

After migrating spring boot to version 3, xml related tests failed.

To fix this issue, migrate from
- javax.xml.bind:jaxb-api:2.4.0-b180830.0359

to
jakarta.xml.bind:jakarta.xml.bind-api:3.0.1

* Configure application insights logging

* Trim logback configuration

Remove no longer required logAppender after removing
app insights

* Update app insights configuration

* Remove bytebuddy dependency

* Remove ApplicationInsights Telemetry configuration

Remove unused Telemetry configuration

* PIC-4117 Remove application insights instrumentation key

Replace application insights instrumentation key with
application_insights_connection_string as per the upgrade to v3
instructions

* Replace ContextInitialiser with custom dimension

Add custom dimenstion with BUILD_NUMBER env value to the
applicationinsights json config file.

This is because ContextInitialiser no longer works after upgrading
app insights